theme: advanced
skin: o2k7
skin_variant: silver
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_buttons1:
- save
- newdocument
- bold
- italic
- underline
- strikethrough
- justifyleft
- justifycenter
- justifyright
- justifyfull
- formatselect
- fontselect
- fontsizeselect
theme_advanced_buttons2: 
- cut
- copy
- paste
- search
- replace
- bullist
- numlist
- outdent
- indent
- blockquote
- undo
- redo
- link
- unlink
- anchor
- image
- cleanup
- forecolor
- backcolor
- code
- preview
- fullscreen
theme_advanced_buttons3:
- tablecontrols
- hr
- removeformat
- sub
- sup
- charmap
- emotions
- iespell
- media
- ltr
- rtl
plugins:
- style
- table
- save
- advimage
- advlink
- inlinepopups
- preview
- media
- searchreplace
- contextmenu
- directionality
- fullscreen
- advlist
